class Dog:
    def __init__(self, name: str = ...) -> None: ...
    @property
    def name(self) -> str: ...
    def woof(self) -> None: ...
    def pet(self, petter: str) -> None: ...
    def play(self, player: str) -> None: ...
